name: Scala CI & Release

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Test JDK ${{ matrix.java }} Scala ${{ matrix.scala }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        scala: [ '2.12.20', '2.13.16' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Run tests for Scala ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} test

  publish-ghp-snapshot:
    name: Publish Snapshot to GitHub Packages
    needs: test
    if: |
      github.event_name == 'push' &&
      github.ref != 'refs/heads/master' &&
      !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Publish Snapshot to GHP
        # No longer need explicit publishTo here, it's handled in build.sbt
        run: sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-sonatype-snapshot:
    name: Publish Snapshot to Sonatype
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Publish Snapshot to Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-sonatype-release:
    name: Publish Release to Sonatype
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Publish Release to Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
